# Copyright (c) 2020 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enable I2C for Cirque trackpad
CONFIG_I2C=y

# Enable Pinnacle driver for Cirque trackpad
CONFIG_PINNACLE=y

# Enable mouse support
CONFIG_ZMK_MOUSE=y

# Enable input module
CONFIG_ZMK_INPUT=y

# Use NFCT pins as GPIO (required for nice!nano v2)
CONFIG_NFCT_PINS_AS_GPIOS=y

# Increase BT power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
